# Generated by Django 4.2.23 on 2026-01-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
