# Generated by Django 4.2.23 on 2026-02-11 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections_app', '0002_voter_email_verification_token_voter_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='restrict_voters',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ElectionVoterEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_voters', to='elections_app.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_eligibilities', to='elections_app.voter')),
            ],
            options={
                'unique_together': {('election', 'voter')},
            },
        ),
    ]
