# Generated by assistant - manual migration to add election FK to Voter and VoterImportFile and conditional unique constraints
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q

class Migration(migrations.Migration):

    dependencies = [
        ('elections_app', '0003_election_restrict_voters_electionvotereligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_voters', to='elections_app.election'),
        ),
        migrations.AddField(
            model_name='voterimportfile',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_imports', to='elections_app.election'),
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(fields=['institution', 'identifier'], condition=Q(election__isnull=True), name='unique_institution_identifier_when_no_election'),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(fields=['election', 'identifier'], condition=Q(election__isnull=False), name='unique_election_identifier_when_election'),
        ),
    ]
