# Generated by assistant - migration for CandidateEvent model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections_app', '0004_add_election_fk_to_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Créé'), ('updated', 'Mis à jour'), ('deleted', 'Supprimé')], default='created', max_length=50)),
                ('candidate_name', models.CharField(max_length=200)),
                ('actor', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='elections_app.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_events', to='elections_app.election')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
